### PR TITLE
Enable Travis

### PR DESCRIPTION
**Pull request by matzew**
@bleathem @sebastienblanc it fails, w/ some wfm modules...

### CODE REVIEW

**Comment by matzew** [comment]
@bleathem @sebastienblanc 

```
Error: Cannot find module '../../lib/wrappers/mediator-client' from '/home/travis/build/feedhenry-raincatcher/raincatcher-appform/test/client'
Error: Cannot find module '../../lib/appform-client' from '/home/travis/build/feedhenry-raincatcher/raincatcher-appform/test/client'
Error: Exit 1
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "node" "/home/travis/.nvm/v0.10.46/bin/npm" "run" "test-phantom"
npm ERR! node v0.10.46
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
npm ERR! fh-wfm-appform@0.0.16 test-phantom: `mochify test/client/**/*.spec.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fh-wfm-appform@0.0.16 test-phantom script 'mochify test/client/**/*.spec.js'.
npm ERR! This is most likely a problem with the fh-wfm-appform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mochify test/client/**/*.spec.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fh-wfm-appform
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/feedhenry-raincatcher/raincatcher-appform/npm-debug.log
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by sebastienblanc** [comment]
@matzew Yes , "known bug" tracked by https://issues.jboss.org/browse/RAINCATCH-105

**Comment by bleathem** [comment]
We should disable the tests that are known to fail, until the upstream issue is resolved.

**Comment by matzew** [comment]
ok, I can update the PR!

On Monday, 4 July 2016, Brian Leathem notifications@github.com wrote:

> We should disable the tests that are known to fail, until the upstream
> issue is resolved.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/feedhenry-raincatcher/raincatcher-appform/pull/3#issuecomment-230339142,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAJnzr0nwdWp4cRddcgKKw5_2JHFKsSEks5qSVGQgaJpZM4JEKeZ
> .

## 

Sent from Gmail Mobile

**Comment by matzew** [comment]
@bleathem @sebastienblanc yo! I am such a hacker!

**Comment by bleathem** [comment]
Great, thanks @matzew

**Pull request merged**
